#                        Copyright (C) 2016 GiantQuartz
#          ____  ___  _________.__      __________        __    __              ____  ___        
#  ___  ___\   \/  / /   _____/|__|_____\______   \__ ___/  |__/  |_  __________\   \/  /___  ___
#  \  \/  / \     /  \_____  \ |  \_  __ \    |  _/  |  \   __\   __\/ __ \_  __ \     / \  \/  /
#   >    <  /     \  /        \|  ||  | \/    |   \  |  /|  |  |  | \  ___/|  | \/     \  >    < 
#  /__/\_ \/___/\  \/_______  /|__||__|  |______  /____/ |__|  |__|  \___  >__| /___/\  \/__/\_ \
#        \/      \_/        \/                  \/                       \/           \_/      \/
#                                                                                                                                                                                  
name: SkyBlockPE
author: xXSirButterXx/xXSirGamesXx
website: http://github.com/xXSirGamesXx
main: SkyBlock\Main
version: "0.1.8"
api:
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7

commands:
  skyblock:
  description: SkyBlockPE commands
  aliases: ["sb", "skyblockpe"]
  
  
permissions:
  skyblock:
  default: true
  description: /sb <args..>


