#  
#          ____  ___  _________.__      __________        __    __              ____  ___        
#  ___  ___\   \/  / /   _____/|__|_____\______   \__ ___/  |__/  |_  __________\   \/  /___  ___
#  \  \/  / \     /  \_____  \ |  \_  __ \    |  _/  |  \   __\   __\/ __ \_  __ \     / \  \/  /
#   >    <  /     \  /        \|  ||  | \/    |   \  |  /|  |  |  | \  ___/|  | \/     \  >    < 
#  /__/\_ \/___/\  \/_______  /|__||__|  |______  /____/ |__|  |__|  \___  >__| /___/\  \/__/\_ \
#        \/      \_/        \/                  \/                       \/           \_/      \/
#                                                                                                                                                                                  
name: SkyBlockPE
author: Zeao
website: §cNot showing due to self-leak information.
main: SkyBlock\Main
version: "1.0.5"
api:
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7

commands:
  version:
   description: Checks the plugin version
   usage: "/is version"
   permission: sbpe.cmd.ver
  changelog:
   description: Change log regarding the server.
   usage: "/is changelog"
   permission: sbpe.cmd.changelog
  reset:
   description: Reset's your island.
   usage: "/is reset"
   permission: sbpe.cmd.reset
  tp:
   description: Tp to an island.
   usage: "/is tp"
   permission: sbpe.command.tp
  remove:
   description: Remove a user.
   usage: "/is remove"
   permission: sbpe.cmd.remove
  leave:
   description: Leave the island.
   usage: "/is leave"
   permission: sbpe.cmd.leave
  makeleader:
   description: Transfer island ownership.
   usage: "/is makeleader"
   permission: sbpe.cmd.makeleader
  delete:
   description: Delete your island.
   usage: "/is delete"
   permission: sbpe.cmd.delete
  members:
   description: Get's a list of island members.
   usage: "/is members"
   permission: sbpe.cmd.members
  deny:
   description: Deny a invite request.
   usage: "/is deny"
   permission: sbpe.cmd.invite.deny
  accept:
   description: Accept's a invite request.
   usage: "/is accept"
   permission: sbpe.cmd.invite.accept
  invite:
   description: Invite a user to your island.
   usage: "/is invite"
   permission: sbpe.cmd.invite
  lock:
   description: Lock/Unlock your island.
   usage: "/is lock"
   permission: sbpe.cmd.lock
  kick:
   description: Kicks a user from your island.
   usage: "/is kick"
   permission: sbpe.cmd.kick
  sethome:
   description: Set homes on an island, (Conmand now aliased)
   usage: "/is sethome"
   permission: sbpe.cmd.sethome
  tphome:
   description: Teleports you home succesfully. (Now aliased to /is home.)
   usage: "/is tphome"
   permission: sbpe.cmd.tphome
  create:
   description: Create an island.
   usage: "/is create"
   permission: sbpe.cmd.create
  go:
   description: Teleports you to your island.
   usage: "/is go"
   permission: sbpe.cmd.go
permissions:
sbpe:
description: Gives skyblock help.
default: true
children:
sbpe.cmd.go:
description: Go to your island.
default: true
sbpe.cmd.create:
description: Create an island.
default: true
sbpe.cmd.tphome:
description: Go to your island home (Command now aliased.)
default: true
sbpe.cmd.sethome:
description: Sethome on your island if you have one (Not working.)
default: op
sbpe.cmd.kick:
description: Kick someone off of your island
default: true
sbpe.cmd.lock:
description: Lock people from coming to your islnd.
default: true
sbpe.cmd.invite:
description: Invite someone
default: true
sbpe.cmd.invite.accept:
description: Accept an invitation
default: true
sbpe.cmd.invite.deny:
description: Deny an invitation 
default: true     
sbpe.cmd.members:
description: See all the members on your island
default: true
sbpe.cmd.delete:
description: Deleted your island 
default: true  
sbpe.cmd.makeleader:
description: Make someone else the leader
default: true
sbpe.cmd.leave:
description: Leave your island.  
default: true
sbpe.cmd.remove:
description: Remove someone
default: true
sbpe.command.tp:
description: Tp to an island
default: op
sbpe.cmd.reset:
description: Reset an island
default: true
sbpe.cmd.changelog:
default: true
sbpe.cmd.ver:
description: get sbpe version
default: true








