#  
#          ____  ___  _________.__      __________        __    __              ____  ___        
#  ___  ___\   \/  / /   _____/|__|_____\______   \__ ___/  |__/  |_  __________\   \/  /___  ___
#  \  \/  / \     /  \_____  \ |  \_  __ \    |  _/  |  \   __\   __\/ __ \_  __ \     / \  \/  /
#   >    <  /     \  /        \|  ||  | \/    |   \  |  /|  |  |  | \  ___/|  | \/     \  >    < 
#  /__/\_ \/___/\  \/_______  /|__||__|  |______  /____/ |__|  |__|  \___  >__| /___/\  \/__/\_ \
#        \/      \_/        \/                  \/                       \/           \_/      \/
#                                                                                                                                                                                  
name: SkyBlockPE
author: xXSirButterXx/xXSirGamesXx
website: http://github.com/xXSirGamesXx
main: SkyBlock\Main
version: "0.1.8"
api:
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7

commands:
  skyblock:
  description: SkyBlockPE commands
  aliases: ["sb", "skyblockpe"]
  permission: sbpe
  
  
permissions:
  sbpe:
  default: true
  description: /sb <args..>
    children:
      sbpe.cmd.join:
        default: true
        description: Join your island.
       sbpe.cmd.create:
        default: true
        description: Create an island.
       sbpe.cmd.home:
        default: true
        description: Go to your island home.
       sbpe.cmd.sethome
        default: true
        description: Sethome on your island if you have one
       sbpe.cmd.kick:
        default: true
        description: Kick someone off of your island
       sbpe.cmd.lock:
        default: true
        description: Lock peole from coming to your islnd.
       sbpe.cmd.invite:
        default: true
        description:
       sbpe.cmd.invite.accept:
        default: true
        description: Accept an invitation
       sbpe.cmd.invite.deny:
        default: true
        description: Deny an invitation      
       sbpe.cmd.members:
        default: true
        description: See all the members on your island
       sbpe.cmd.disband:
        default: true
        description: Disband your island   
       sbpe.cmd.makeleader:
        default: true
        description: Make someone else the leader
       sbpe.cmd.leave:
        default: true
        description: Leave your island.
       sbpe.cmd.remove:
        default: true
        description: Remove someoen
       sbpe.cmd.tp:
        default: op
        description: Tp to an island
       sbpe.cmd.reset:
        default: true
        description: Reset an island
       sbpe.cmd.ver:
        default: true
        description: get sbpe version
       sbpe.cmd.help
        default: true
        description: Get skyblock help
        
        
        
      


