#  
#          ____  ___  _________.__      __________        __    __              ____  ___        
#  ___  ___\   \/  / /   _____/|__|_____\______   \__ ___/  |__/  |_  __________\   \/  /___  ___
#  \  \/  / \     /  \_____  \ |  \_  __ \    |  _/  |  \   __\   __\/ __ \_  __ \     / \  \/  /
#   >    <  /     \  /        \|  ||  | \/    |   \  |  /|  |  |  | \  ___/|  | \/     \  >    < 
#  /__/\_ \/___/\  \/_______  /|__||__|  |______  /____/ |__|  |__|  \___  >__| /___/\  \/__/\_ \
#        \/      \_/        \/                  \/                       \/           \_/      \/
#                                                                                                                                                                                  
name: SkyBlockPE
author: Zeao
website: Not showing due to self-leak information.
main: SkyBlock\Main
version: "1.0.1"
api:
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7

commands:
  skyblock:
  description: SkyBlockPE commands
  aliases: ["sb", "is", "island"]
  go:
  description: Teleport to your island.
  aliases: ["join", "home"]
  create:
  description: Create your island.
  aliases: ["make"]
  tphome:
  description: Teleport you to your home."
  aliases: []
  sethome:
  description: Set home at your island.
  aliases: ["makehome", "addhome"]
  kick:
  description: Kicks a player from the island.
  aliases: ["expel"]
  lock:
  description: Locks/Unlocks an island.
  aliases: ["togglelock"]
  invite:
  description: Invites a user to your island.
  aliases: ["ask"]
  accept:
  description: Accepts a island invite.
  aliases: ["yes"]
  deny:
  description: Denies a island request.
  aliases: ["no", "reject"]
  members:
  description: List members in your island.
  aliases: ["listmembers", "ourmembers"]
  delete:
  description: Delete's your island.
  aliases: ["disband"]
  makeleader:
  description: Transfer's a new leader.
  aliases: ["newleader"]
  leave:
  description: Leaves your island.
  aliases: ["quit"]
  remove:
  description: Remove's a user from your island.
  aliases: ["takeaway"]
  tp:
  description: Teleports you to another island.
  aliases: ["tpto"]
  reset:
  description: Reset's your island to default.
  aliases: ["clear"]
  changelog:
  description: Checks our latest change log.
  aliases: ["clog"]
  version:
  description: Checks for the latest plugin version.
  aliases: ["ver"]
  
  
permissions:
sbpe:
description: Gives skyblock help.
default: true
sbpe.cmd.go:
description: Go to your island.
default: true
sbpe.cmd.create:
description: Create an island.
default: true
sbpe.cmd.tphome:
description: Go to your island home (Command now aliased.)
default: true
sbpe.cmd.sethome:
description: Sethome on your island if you have one (Not working.)
default: op
sbpe.cmd.kick:
description: Kick someone off of your island
default: true
sbpe.cmd.lock:
description: Lock people from coming to your islnd.
default: true
sbpe.cmd.invite:
description: Invite someone
default: true
sbpe.cmd.invite.accept:
description: Accept an invitation
default: true
sbpe.cmd.invite.deny:
description: Deny an invitation 
default: true     
sbpe.cmd.members:
description: See all the members on your island
default: true
sbpe.cmd.delete:
description: Deleted your island 
default: true  
sbpe.cmd.makeleader:
description: Make someone else the leader
default: true
sbpe.cmd.leave:
description: Leave your island.  
default: true
sbpe.cmd.remove:
description: Remove someone
default: true
sbpe.command.tp:
description: Tp to an island
default: op
sbpe.cmd.reset:
description: Reset an island
default: true
sbpe.cmd.changelog:
default: true
sbpe.cmd.ver:
description: get sbpe version
default: true








