#  
#          ____  ___  _________.__      __________        __    __              ____  ___        
#  ___  ___\   \/  / /   _____/|__|_____\______   \__ ___/  |__/  |_  __________\   \/  /___  ___
#  \  \/  / \     /  \_____  \ |  \_  __ \    |  _/  |  \   __\   __\/ __ \_  __ \     / \  \/  /
#   >    <  /     \  /        \|  ||  | \/    |   \  |  /|  |  |  | \  ___/|  | \/     \  >    < 
#  /__/\_ \/___/\  \/_______  /|__||__|  |______  /____/ |__|  |__|  \___  >__| /___/\  \/__/\_ \
#        \/      \_/        \/                  \/                       \/           \_/      \/
#                                                                                                                                                                                  
name: SkyBlockPE
author: xXSirButterXx/xXSirGamesXx, edited by Zeao.
website: Not showing due to self-leak information.
main: SkyBlock\Main
version: "0.1.9"
api:
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.1

commands:
  island:
  description: SkyBlockPE commands
  aliases: ["is", "skyblock"]
  permission: sbpe
  
  
permissions:
sbpe:
description: /sb <args..>
default: true
sbpe.cmd.join:
description: Join your island.
default: true
sbpe.cmd.create:
description: Create an island.
default: true
sbpe.cmd.home:
description: Go to your island home
default: true
sbpe.cmd.sethome:
description: Sethome on your island if you have one
default: true
sbpe.cmd.kick:
description: Kick someone off of your island
default: true
sbpe.cmd.lock:
description: Lock people from coming to your islnd.
default: true
sbpe.cmd.invite:
description: Invite someone
default: true
sbpe.cmd.invite.accept:
description: Accept an invitation
default: true
sbpe.cmd.invite.deny:
description: Deny an invitation 
default: true     
sbpe.cmd.members:
description: See all the members on your island
default: true
sbpe.cmd.disband:
description: Disband your island 
default: true  
sbpe.cmd.makeleader:
description: Make someone else the leader
default: true
sbpe.cmd.leave:
description: Leave your island.  
default: true
sbpe.cmd.remove:
description: Remove someone
default: true
sbpe.cmd.tp:
description: Tp to an island
default: op
sbpe.cmd.reset:
description: Reset an island
default: true
sbpe.cmd.ver:
description: get sbpe version
default: true
